### ISSUE TITLE
WCF最新版没有 wcf.exe

### ISSUE THREAD

**Issue by keryul** [dr-forget/wcferry-node#1]
[WCF 最新版](https://github.com/lich0821/WeChatFerry/releases/tag/v39.2.2)没有 wcf.exe
是否可以用旧版的

**Comment by dr-forget** [comment]
新版  不在需要wcf.exe  直接调用dll即可  如你还需要exe的启动方式   此sdk也实现了wcf.exe 启动器  使用新版2.0.2 即可

**Comment by dr-forget** [comment]
> [WCF 最新版](https://github.com/lich0821/WeChatFerry/releases/tag/v39.2.2)没有 wcf.exe 是否可以用旧版的

新版 不在需要wcf.exe 直接调用dll即可 如你还需要exe的启动方式 此sdk也实现了wcf.exe 启动器 使用新版2.0.2 即可
