### ISSUE TITLE
撤回消息始终返回的-1

### ISSUE THREAD

**Issue by Jxells** [dr-forget/wcferry-node#4]

**Comment by dr-forget** [comment]
新版wcfsdk 不支持 如需功能 请使用 v1版本 3.9.2.23

**Comment by lcwh52** [comment]
使用 v1版本 3.9.2.23
无法运行，报tcp://127.0.0.1:10086 无法连接
v1版本有示例demo吗

**Comment by dr-forget** [comment]
V1版本只支持host模式啊，文档写的清清楚楚，不支持本地启动，代码都是一样的

**Comment by dr-forget** [comment]
v1版本自用的，老版本需要一个wcf服务
