### ISSUE TITLE
作为client端发送下载图片请求总是超时错误

### ISSUE THREAD

**Issue by lblblong** [dr-forget/wcferry-node#6]
client 运行在 mac 上

![QQ_1729479921256](https://github.com/user-attachments/assets/a17c6bcf-0122-4a2d-8d49-48c4b9829e1a)

**Comment by dr-forget** [comment]
最新版sdk更新至2.1.14
3.9.2.23 sdk 更新至 2.0.21
wcf 实例新增wechat_dir 参数 示例如下

```javascript
const wcferry = new Wcferry({
    host: "192.168.1.2",
    port: 10086,
    wechat_dir:       //默认安装路径为:C:/Users/Administrator/Documents/WeChat Files  请填写为实际安装路径 否则下载附件报错  
    // 填写事项：安装目录只需填写 WeChat Files 前部分即可
    // 例如 完整路径 D:/data/tenter/wechat/WeChat Files 
   //  wechat_dir 填写  D:/data/tenter/wechat 即可Ï
 });
```

**Comment by lblblong** [comment]
还是报错，我试了安装路径也试了 Wechat Files 这个路径
![QQ_1729676787963](https://github.com/user-attachments/assets/b96df641-e5fd-4fef-b595-80d8a4c28da2)

报错和之前一样：
![QQ_1729676836701](https://github.com/user-attachments/assets/c8872047-f33f-44e9-b37b-f11b8eb82092)

**Comment by dr-forget** [comment]
> 还是报错，我试了安装路径也试了 Wechat Files 这个路径 ![QQ_1729676787963](https://private-user-images.githubusercontent.com/18625523/379207255-b96df641-e5fd-4fef-b595-80d8a4c28da2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3Mzc0MzUsIm5iZiI6MTcyOTczNzEzNSwicGF0aCI6Ii8xODYyNTUyMy8zNzkyMDcyNTUtYjk2ZGY2NDEtZTVmZC00ZmVmLWI1OTUtODBkOGE0YzI4ZGEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDAyMzIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlZGQ2NjJjNGMyNWM3ZTZlNzJlNjljZmEwNmRjY2UzY2ZhM2NmNjM4NmI4NWZiMDdkNjc0MTViNDQ2MzU4YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ado3EvSlEupuLUOKOmrlZWrHSd1bqHEpLV69_AU8BGw)
> 
> 报错和之前一样： ![QQ_1729676836701](https://private-user-images.githubusercontent.com/18625523/379207633-c8872047-f33f-44e9-b37b-f11b8eb82092.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3Mzc0MzUsIm5iZiI6MTcyOTczNzEzNSwicGF0aCI6Ii8xODYyNTUyMy8zNzkyMDc2MzMtYzg4NzIwNDctZjMzZi00NGU5LWIzN2ItZjExYjhlYjgyMDkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDAyMzIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5NzZkZWU2ZWY3NjBjMDgwZDEyMzRjNTA3NTU1NDFiY2Q1MGYxYzAzYmJmZmMzMmEwZmQ5YWU5ZDNhOTJiZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MtYz1CPcCyxY7Nn-ewicywBamfiRiSLVHQbmPUdcc0M)

你看下客户端wcf log.txt 的日志贴下

**Comment by dr-forget** [comment]
<img width="1232" alt="image" src="https://github.com/user-attachments/assets/df9b5b6e-14b0-4f7f-b140-8f633e1921a0">
v1 版本我测试了没问题 最新版我没有用 就没测试  应该是一样的

**Comment by dr-forget** [comment]
<img width="1012" alt="image" src="https://github.com/user-attachments/assets/df76b5b5-d5e9-4f22-b8ba-e99820a4c3b6">
v1版本我测试了没问题  最新版因为我没有使用 但是应该也是一样的

**Comment by lblblong** [comment]
我修改目录为 C:/Users/name/Documents/WeChat Files 就可以了，我看日志是有在写文件的，但是写失败了，写的路径在那台运行 service 的机器上是可以写的

![QQ_1729763332669](https://github.com/user-attachments/assets/5b1e3a41-7e40-461b-854c-21cef3569079)

![image](https://github.com/user-attachments/assets/270ca319-73dd-4552-9a9f-40fb55f7b109)

然后我在c盘直接新建了一个 app 文件夹，也写不进去
![image](https://github.com/user-attachments/assets/e045439c-9904-403d-b4d0-0b2468902afe)

**Comment by lblblong** [comment]
> @lblblong c盘只能写用户目录 其他目录没权限的 系统设定的安全策略 你存到c盘以外的盘试试

在那台机器上直接跑本地模式是可以正常写入这个路径的：C:\\Users\\MATSON FURNITURE\\code\\wechaty\\images
但是改成 service + client 模式之后，就写失败了

我们那个同事的机器只有一个分区...

**Comment by lblblong** [comment]
> 刚测过了 没问题的 你仔细排查下 路径 c盘的盘符小写看看

c 盘符小写果然可以了....，谢谢大佬！

**Comment by lblblong** [comment]
大佬，可以下载图片之外的其他文件吗

**Comment by dr-forget** [comment]
可以 图片、视频  附件都行

**Comment by lblblong** [comment]
大佬，除了图片之外，其他的下载都会失败


![QQ_1730084677530](https://github.com/user-attachments/assets/dd9e67bc-1c17-4bff-81a1-8a7204e67ab2)

![image](https://github.com/user-attachments/assets/ece27f12-85a1-4fce-83a1-fdca3cf4cca2)

**Comment by dr-forget** [comment]
文件名不要是中文 中文好像不行

**Comment by lblblong** [comment]
> 文件名不要是中文 中文好像不行

通过文件夹同步工具解决这个问题了，但是又有个新的问题，连续收到多张图片的时候，偶尔会出现下载失败的情况：
![QQ_1730194870095](https://github.com/user-attachments/assets/774eaffa-9e31-4ccd-a44a-f24d70207e30)

**Comment by dr-forget** [comment]
数据量大的情况 尽量传入extra 参数  extra 不传会从数据库查 耗时 异步的问题
